import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Header from "@/components/layout/Header";
import DarkModeWrapper from "@/components/layout/DarkModeWrapper";
import SideBar from "@/components/layout/SideBar/SideBar";
import Footer from "@/components/layout/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-hidden`}
      >
        <DarkModeWrapper>
          <div className="grid h-screen grid-rows-[auto_1fr_auto] grid-cols-[240px_1fr]">
            <Header />
            <SideBar />
            <main className="overflow-y-auto overflow-x-hidden p-4">
              {children}
            </main>
            <Footer />
          </div>
        </DarkModeWrapper>
      </body>
    </html>
  );
}

