import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Header from "@/components/layout/Header";
import DarkModeWrapper from "@/components/layout/DarkModeWrapper";
import SideBar from "@/components/layout/SideBar/SideBar";
import Footer from "@/components/layout/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log("Root Layout Rendered");
  
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <DarkModeWrapper>
      <Header/>
      <SideBar/>
      <div className=" min-h-screen">
      <div className="flex-1 overflow-y-auto">{children}</div>
      <Footer />
      </div>
      </DarkModeWrapper>
      </body>
    </html>
  );
}
